# Generated by Django 2.2.13 on 2020-07-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horecacsvexport',
            options={'ordering': ('-isoyear', '-isoweek', '-created_at')},
        ),
    ]
