# Generated by Django 2.2.13 on 2020-07-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0114_category_changes_SIG-2872'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_level_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_level_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_level_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_level_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='stadsdeel',
            field=models.CharField(choices=[('A', 'Centrum'), ('B', 'Westpoort'), ('E', 'West'), ('M', 'Oost'), ('N', 'Noord'), ('T', 'Zuidoost'), ('K', 'Zuid'), ('F', 'Nieuw-West'), ('H', 'Het Amsterdamse Bos'), ('W', 'Weesp')], max_length=1, null=True),
        ),
    ]
