# Generated by Django 2.2.13 on 2020-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0117_remove_category_slug_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_level_1',
            new_name='category_level_name1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_level_2',
            new_name='category_level_name2',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_level_3',
            new_name='category_level_name3',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_level_4',
            new_name='category_level_name4',
        ),
    ]
