# Generated by Django 2.2.13 on 2020-07-31 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signals', '0118_auto_20200731_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_days', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('report_time', models.TimeField()),
                ('forman_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='signals.Reporter')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='signals.Signal')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
