# Generated by Django 2.2.13 on 2020-07-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0119_signalsplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.City'),
        ),
        migrations.AddField(
            model_name='department',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.Country'),
        ),
        migrations.AddField(
            model_name='signal',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.City'),
        ),
        migrations.AddField(
            model_name='signal',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.Country'),
        ),
    ]
