# Generated by Django 2.2.13 on 2020-07-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0120_auto_20200731_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='country_id',
            new_name='country',
        ),
    ]
