# Generated by Django 2.2.13 on 2020-07-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0121_auto_20200731_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.City'),
        ),
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.Country'),
        ),
    ]
