# Generated by Django 2.2.13 on 2020-08-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0122_auto_20200731_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalsActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_id', models.CharField(max_length=255)),
                ('to_app', models.CharField(max_length=255)),
                ('from_app', models.CharField(max_length=255)),
                ('signal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signals.Signal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
