# Generated by Django 2.2.13 on 2020-08-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0123_signalsactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
