# Generated by Django 2.2.13 on 2020-08-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0124_auto_20200803_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalsplan',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='signalsplan',
            old_name='report_id',
            new_name='report',
        ),
        migrations.AlterField(
            model_name='signalsactivity',
            name='activity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
