# Generated by Django 2.2.13 on 2020-08-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0125_auto_20200805_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signalsplan',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='signalsplan',
            name='report_time',
        ),
    ]
