# Generated by Django 2.2.13 on 2020-08-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0126_auto_20200805_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalsplan',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='signals.Signal'),
        ),
    ]
