# Generated by Django 2.2.13 on 2020-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0127_auto_20200805_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalsplan',
            old_name='report',
            new_name='signal',
        ),
        migrations.AddField(
            model_name='signalsplan',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
