# Generated by Django 2.2.13 on 2020-08-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0129_auto_20200807_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalsplan',
            old_name='emp',
            new_name='reporter',
        ),
        migrations.RenameField(
            model_name='signalsplan',
            old_name='schedule',
            new_name='schedule_datetime',
        ),
    ]
