# Generated by Django 2.2.13 on 2020-08-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0130_auto_20200808_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='finished_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
