# Generated by Django 2.2.13 on 2020-08-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0133_auto_20200817_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='city_object',
        ),
        migrations.AddField(
            model_name='category',
            name='new_slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CityObjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('_signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_object_assignments', to='signals.Signal')),
                ('city_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_object_assignments', to='signals.CityObject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
