# Generated by Django 2.2.13 on 2020-08-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0134_auto_20200821_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='city_object',
            field=models.ManyToManyField(blank=True, through='signals.CityObjectAssignment', to='signals.CityObject'),
        ),
    ]
