# Generated by Django 2.2.13 on 2020-08-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0137_auto_20200821_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cityobject',
            old_name='orac_commment',
            new_name='orac_comment',
        ),
    ]
