# Generated by Django 2.2.13 on 2020-08-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0138_auto_20200822_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signalcityobject',
            old_name='signal_id',
            new_name='signal',
        ),
        migrations.RemoveField(
            model_name='cityobjectassignment',
            name='text',
        ),
    ]
