# Generated by Django 2.2.13 on 2020-08-21 19:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20200719_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horecacsvexport',
            name='uploaded_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/dwh_media'), upload_to='exports/%Y'),
        ),
    ]
