# Generated by Django 2.2.13 on 2020-08-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='type',
            new_name='_type',
        ),
    ]
